In [1]:
import pandas as pd

In [4]:
df  = pd.DataFrame({'a':[1,2,3,4,4],'b':[3,4,5,6,9],'c':[0,45,89,229,40]})

In [5]:
df

   a  b    c
0  1  3    0
1  2  4   45
2  3  5   89
3  4  6  229
4  4  9   40

In [21]:
data = {'Name':["Aditya", 'Anu','Arsh','Moksh','Himanshu'],'course':['Python DS','Python DS','Python DS','Python Langchain','Python Langchain'],"roll no.":[1,2,3,4,5]}

In [22]:
df1 = pd.DataFrame(data,index=['a','b','c','d','e'])

In [23]:
df1

       Name            course  roll no.
a    Aditya         Python DS         1
b       Anu         Python DS         2
c      Arsh         Python DS         3
d     Moksh  Python Langchain         4
e  Himanshu  Python Langchain         5

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5 non-null      object
 1   course    5 non-null      object
 2   roll no.  5 non-null      int64
dtypes: int64(1), object(2)
memory usage: 160.0+ bytes

In [13]:
df1['roll no.'].sum()

15

In [24]:
df1.course.value_counts()

course
Python DS           3
Python Langchain    2
Name: count, dtype: int64

In [26]:
df1.loc['a':'b','Name':'course']

     Name     course
a  Aditya  Python DS
b     Anu  Python DS

In [29]:
df1.iloc[0:2,0:2]

     Name     course
a  Aditya  Python DS
b     Anu  Python DS

In [35]:
df3 = pd.DataFrame([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],columns= ['a','b','c','d','e'])

In [33]:
df3

    a   b   c   d   e
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15

In [37]:
df1.shape

(5, 3)

In [38]:
df3.shape

(3, 5)

In [39]:
df1

       Name            course  roll no.
a    Aditya         Python DS         1
b       Anu         Python DS         2
c      Arsh         Python DS         3
d     Moksh  Python Langchain         4
e  Himanshu  Python Langchain         5

In [40]:
df1.loc[:,'roll no.'] = [4,5,6,7,8]

In [41]:
df1

       Name            course  roll no.
a    Aditya         Python DS         4
b       Anu         Python DS         5
c      Arsh         Python DS         6
d     Moksh  Python Langchain         7
e  Himanshu  Python Langchain         8

In [42]:
df1.loc[:,'degree'] = 'B. Tech'

In [43]:
df1

       Name            course  roll no.   degree
a    Aditya         Python DS         4  B. Tech
b       Anu         Python DS         5  B. Tech
c      Arsh         Python DS         6  B. Tech
d     Moksh  Python Langchain         7  B. Tech
e  Himanshu  Python Langchain         8  B. Tech