In [18]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder #pip install scikit-learn

In [2]:
df  = pd.read_csv("airlines.csv")

In [3]:
df.head()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [4]:
df.drop("index", axis = 1, inplace = True)

In [5]:
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [6]:
df.airline.value_counts()

airline
Vistara      127859
Air_India     80892
Indigo        43120
GO_FIRST      23173
AirAsia       16098
SpiceJet       9011
Name: count, dtype: int64

In [8]:
enc  = OneHotEncoder()

In [ ]:
#fit - read
#transform - process 
#fit - transform

In [9]:
enc.fit(df.loc[:,["airline"]])

OneHotEncoder()

In [ ]:
a_trans = enc.transform(df.loc[:,["airline"]]).toarray()

In [ ]:
# red  - 0
# blue - 1
# red - 0 
# blue - 1

SyntaxError: invalid syntax (1027188249.py, line 1)

In [12]:
a_trans

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.]])

In [13]:
enc.get_feature_names_out()

array(['airline_AirAsia', 'airline_Air_India', 'airline_GO_FIRST',
       'airline_Indigo', 'airline_SpiceJet', 'airline_Vistara'],
      dtype=object)

In [14]:
df.loc[:,enc.get_feature_names_out()] = a_trans

In [15]:
df.head(10)

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,airline_AirAsia,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,airline_Vistara
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,0.0,0.0,0.0,0.0,1.0,0.0
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,0.0,0.0,0.0,0.0,1.0,0.0
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,1.0,0.0,0.0,0.0,0.0,0.0
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,0.0,0.0,0.0,0.0,0.0,1.0
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,0.0,0.0,0.0,0.0,0.0,1.0
5,Vistara,UK-945,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955,0.0,0.0,0.0,0.0,0.0,1.0
6,Vistara,UK-927,Delhi,Morning,zero,Morning,Mumbai,Economy,2.08,1,6060,0.0,0.0,0.0,0.0,0.0,1.0
7,Vistara,UK-951,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6060,0.0,0.0,0.0,0.0,0.0,1.0
8,GO_FIRST,G8-334,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5954,0.0,0.0,1.0,0.0,0.0,0.0
9,GO_FIRST,G8-336,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954,0.0,0.0,1.0,0.0,0.0,0.0

In [16]:
df.drop("airline", axis= 1, inplace = True)

In [17]:
df.head()

,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,airline_AirAsia,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,airline_Vistara
0,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,0.0,0.0,0.0,0.0,1.0,0.0
1,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,0.0,0.0,0.0,0.0,1.0,0.0
2,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,1.0,0.0,0.0,0.0,0.0,0.0
3,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,0.0,0.0,0.0,0.0,0.0,1.0
4,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,0.0,0.0,0.0,0.0,0.0,1.0

#LabelEncoder

In [19]:
label = LabelEncoder()

In [20]:
df.source_city.value_counts()

source_city
Delhi        61343
Mumbai       60896
Bangalore    52061
Kolkata      46347
Hyderabad    40806
Chennai      38700
Name: count, dtype: int64

In [21]:
ans = label.fit_transform(df.loc[:,['source_city']])

C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [22]:
ans

array([2, 2, 2, ..., 1, 1, 1])

In [23]:
df.insert(loc = 1, column = "s_city_enc",value = ans)

In [24]:
df

,flight,s_city_enc,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,airline_AirAsia,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,airline_Vistara
0,SG-8709,2,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,0.0,0.0,0.0,0.0,1.0,0.0
1,SG-8157,2,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,0.0,0.0,0.0,0.0,1.0,0.0
2,I5-764,2,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,1.0,0.0,0.0,0.0,0.0,0.0
3,UK-995,2,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,0.0,0.0,0.0,0.0,0.0,1.0
4,UK-963,2,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,UK-822,1,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,0.0,0.0,0.0,0.0,0.0,1.0
300149,UK-826,1,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,0.0,0.0,0.0,0.0,0.0,1.0
300150,UK-832,1,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,0.0,0.0,0.0,0.0,0.0,1.0
300151,UK-828,1,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,0.0,0.0,0.0,0.0,0.0,1.0
300152,UK-822,1,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,0.0,0.0,0.0,0.0,0.0,1.0