In [30]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv("diabetes.csv")

In [3]:
df.head(10)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
5,Female,20.0,0,0,never,27.32,6.6,85,0
6,Female,44.0,0,0,never,19.31,6.5,200,1
7,Female,79.0,0,0,No Info,23.86,5.7,85,0
8,Male,42.0,0,0,never,33.64,4.8,145,0
9,Female,32.0,0,0,never,27.32,5.0,100,0

In [4]:
enc = LabelEncoder()

In [5]:
gender_enc = enc.fit_transform(df.gender)
smoking_enc = enc.fit_transform(df.smoking_history)

In [6]:
df.insert(loc=0, column="Gender_enc", value = gender_enc)
df.insert(loc=4, column="Smoking_hist_enc", value = smoking_enc)

In [7]:
df.head(50)

,Gender_enc,gender,age,hypertension,Smoking_hist_enc,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,Female,80.0,0,4,1,never,25.19,6.6,140,0
1,0,Female,54.0,0,0,0,No Info,27.32,6.6,80,0
2,1,Male,28.0,0,4,0,never,27.32,5.7,158,0
3,0,Female,36.0,0,1,0,current,23.45,5.0,155,0
4,1,Male,76.0,1,1,1,current,20.14,4.8,155,0
5,0,Female,20.0,0,4,0,never,27.32,6.6,85,0
6,0,Female,44.0,0,4,0,never,19.31,6.5,200,1
7,0,Female,79.0,0,0,0,No Info,23.86,5.7,85,0
8,1,Male,42.0,0,4,0,never,33.64,4.8,145,0
9,0,Female,32.0,0,4,0,never,27.32,5.0,100,0
10,0,Female,53.0,0,4,0,never,27.32,6.1,85,0
11,0,Female,54.0,0,3,0,former,54.70,6.0,100,0
12,0,Female,78.0,0,3,0,former,36.05,5.0,130,0
13,0,Female,67.0,0,4,0,never,25.69,5.8,200,0
14,0,Female,76.0,0,0,0,No Info,27.32,5.0,160,0
15,1,Male,78.0,0,0,0,No Info,27.32,6.6,126,0
16,1,Male,15.0,0,4,0,never,30.36,6.1,200,0
17,0,Female,42.0,0,4,0,never,24.48,5.7,158,0
18,0,Female,42.0,0,0,0,No Info,27.32,5.7,80,0
19,1,Male,37.0,0,2,0,ever,25.72,3.5,159,0
20,1,Male,40.0,0,1,0,current,36.38,6.0,90,0
21,1,Male,5.0,0,0,0,No Info,18.80,6.2,85,0
22,0,Female,69.0,0,4,0,never,21.24,4.8,85,0
23,0,Female,72.0,0,3,1,former,27.94,6.5,130,0
24,0,Female,4.0,0,0,0,No Info,13.99,4.0,140,0
25,1,Male,30.0,0,4,0,never,33.76,6.1,126,0
26,1,Male,67.0,0,5,1,not current,27.32,6.5,200,1
27,1,Male,40.0,0,3,0,former,27.85,5.8,80,0
28,1,Male,45.0,1,4,0,never,26.47,4.0,158,0
29,1,Male,43.0,0,4,0,never,26.08,6.1,155,0
30,0,Female,53.0,0,0,0,No Info,31.75,4.0,200,0
31,1,Male,50.0,0,0,0,No Info,25.15,4.0,145,0
32,0,Female,41.0,0,1,0,current,22.01,6.2,126,0
33,0,Female,20.0,0,4,0,never,22.19,3.5,100,0
34,0,Female,76.0,0,4,0,never,23.55,5.0,85,0
35,1,Male,5.0,0,0,0,No Info,15.10,5.8,85,0
36,0,Female,15.0,0,0,0,No Info,21.76,4.5,130,0
37,0,Female,26.0,0,4,0,never,21.22,6.6,200,0
38,1,Male,50.0,1,1,0,current,27.32,5.7,260,1
39,0,Female,34.0,0,4,0,never,56.43,6.2,200,0
40,1,Male,73.0,0,3,0,former,25.91,9.0,160,1
41,1,Male,5.0,0,0,0,No Info,27.32,6.6,130,0
42,0,Female,77.0,1,4,1,never,32.02,5.0,159,0
43,0,Female,66.0,0,0,0,No Info,29.30,4.8,159,0
44,0,Female,67.0,0,0,0,No Info,27.32,3.5,160,0
45,0,Female,44.0,0,4,0,never,24.93,6.1,100,0
46,0,Female,29.0,0,4,0,never,19.95,5.0,90,0
47,0,Female,60.0,0,4,0,never,18.03,4.0,159,0
48,0,Female,38.0,0,4,0,never,28.27,6.2,155,0
49,0,Female,3.0,0,0,0,No Info,19.27,6.5,100,0

In [8]:
df.smoking_history.value_counts()

smoking_history
No Info        35816
never          35095
former          9352
current         9286
not current     6447
ever            4004
Name: count, dtype: int64

In [9]:
df.Smoking_hist_enc.value_counts()

Smoking_hist_enc
0    35816
4    35095
3     9352
1     9286
5     6447
2     4004
Name: count, dtype: int64

In [10]:
df.drop(columns = ['gender', 'smoking_history'], inplace = True)

In [11]:
df.diabetes.value_counts()

diabetes
0    91500
1     8500
Name: count, dtype: int64

In [12]:
df.rename(columns={'diabetes' : 'target'}, inplace = True)

In [13]:
df.head()

,Gender_enc,age,hypertension,Smoking_hist_enc,heart_disease,bmi,HbA1c_level,blood_glucose_level,target
0,0,80.0,0,4,1,25.19,6.6,140,0
1,0,54.0,0,0,0,27.32,6.6,80,0
2,1,28.0,0,4,0,27.32,5.7,158,0
3,0,36.0,0,1,0,23.45,5.0,155,0
4,1,76.0,1,1,1,20.14,4.8,155,0

In [15]:
df.target.value_counts()

target
0    91500
1     8500
Name: count, dtype: int64

In [16]:
x = df.iloc[:, :-1]

In [17]:
y = df.iloc[:,-1]

In [18]:
x

,Gender_enc,age,hypertension,Smoking_hist_enc,heart_disease,bmi,HbA1c_level,blood_glucose_level
0,0,80.0,0,4,1,25.19,6.6,140
1,0,54.0,0,0,0,27.32,6.6,80
2,1,28.0,0,4,0,27.32,5.7,158
3,0,36.0,0,1,0,23.45,5.0,155
4,1,76.0,1,1,1,20.14,4.8,155
...,...,...,...,...,...,...,...,...
99995,0,80.0,0,0,0,27.32,6.2,90
99996,0,2.0,0,0,0,17.37,6.5,100
99997,1,66.0,0,3,0,27.83,5.7,155
99998,0,24.0,0,4,0,35.42,4.0,100
99999,0,57.0,0,1,0,22.43,6.6,90

In [19]:
y

0        0
1        0
2        0
3        0
4        0
        ..
99995    0
99996    0
99997    0
99998    0
99999    0
Name: target, Length: 100000, dtype: int64

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2,random_state = 35)

In [21]:
x_train

,Gender_enc,age,hypertension,Smoking_hist_enc,heart_disease,bmi,HbA1c_level,blood_glucose_level
85308,0,22.0,0,1,0,21.75,5.0,130
94200,0,70.0,1,4,0,38.41,5.7,155
13503,1,25.0,0,1,0,27.32,5.0,100
28991,1,37.0,0,0,0,27.32,6.0,158
34618,0,6.0,0,0,0,27.32,5.8,100
...,...,...,...,...,...,...,...,...
84927,0,57.0,0,4,0,33.63,6.2,130
56300,0,12.0,0,4,0,18.40,6.1,158
48161,0,24.0,0,5,0,20.63,6.5,130
41911,1,18.0,0,4,0,29.29,4.8,140
71369,0,61.0,0,4,0,30.04,5.7,100

In [22]:
y_train

85308    0
94200    0
13503    0
28991    0
34618    0
        ..
84927    0
56300    0
48161    0
41911    0
71369    0
Name: target, Length: 80000, dtype: int64

In [31]:
# dt = DecisionTreeClassifier()
# lr  = LogisticRegression()
rf = RandomForestClassifier(n_estimators=9)

In [32]:
rf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=9)

In [33]:
y_test

26369    1
23524    0
82990    0
77073    0
61189    0
        ..
19118    0
40921    0
84236    0
63785    0
57695    0
Name: target, Length: 20000, dtype: int64

In [34]:
pred = rf.predict(x_test)

In [35]:
accuracy_score(y_test,pred)

0.96865

In [28]:
import joblib

In [36]:
joblib.dump(rf,"diabeat.pkl")

['diabeat.pkl']

In [ ]:
import numpy as np

In [ ]:
val = np.array([0,30,0,4,0,22,5.5,120])

In [ ]:
model = joblib.load("diabeat.pkl")

In [ ]:
model.predict([val])

C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)